/// <reference types='vite-plus/test' />
/// <reference types='vite-plus/client' />

import { defineConfig, lazyPlugins } from 'vite-plus';
import react from '@vitejs/plugin-react';

// https://vitejs.dev/config/
export default defineConfig({
  staged: {
    '*': 'vp check --fix',
  },
  fmt: {},
  lint: {
    plugins: ['oxc', 'typescript', 'unicorn', 'react', 'jsx-a11y'],
    jsPlugins: [
      {
        name: 'vite-plus',
        specifier: 'vite-plus/oxlint-plugin',
      },
    ],
    categories: {
      correctness: 'warn',
    },
    options: {
      typeAware: true,
      typeCheck: true,
    },
    env: {
      builtin: true,
      es2025: true,
      browser: true,
    },
    settings: {
      'react-x': {
        version: 'detect',
        importSource: 'react',
        polymorphicPropName: 'as',
      },
    },
    ignorePatterns: ['dist', 'build'],
    rules: {
      'constructor-super': 'error',
      'for-direction': 'error',
      'getter-return': 'error',
      'no-async-promise-executor': 'error',
      'no-case-declarations': 'error',
      'no-class-assign': 'error',
      'no-compare-neg-zero': 'error',
      'no-cond-assign': 'error',
      'no-const-assign': 'error',
      'no-constant-binary-expression': 'error',
      'no-constant-condition': 'error',
      'no-control-regex': 'error',
      'no-debugger': 'error',
      'no-delete-var': 'error',
      'no-dupe-class-members': 'error',
      'no-dupe-else-if': 'error',
      'no-dupe-keys': 'error',
      'no-duplicate-case': 'error',
      'no-empty': 'error',
      'no-empty-character-class': 'error',
      'no-empty-pattern': 'error',
      'no-empty-static-block': 'error',
      'no-ex-assign': 'error',
      'no-extra-boolean-cast': 'error',
      'no-fallthrough': 'error',
      'no-func-assign': 'error',
      'no-global-assign': 'error',
      'no-import-assign': 'error',
      'no-invalid-regexp': 'error',
      'no-irregular-whitespace': 'error',
      'no-loss-of-precision': 'error',
      'no-misleading-character-class': 'error',
      'no-new-native-nonconstructor': 'error',
      'no-nonoctal-decimal-escape': 'error',
      'no-obj-calls': 'error',
      'no-prototype-builtins': 'error',
      'no-redeclare': 'error',
      'no-regex-spaces': 'error',
      'no-self-assign': 'error',
      'no-setter-return': 'error',
      'no-shadow-restricted-names': 'error',
      'no-sparse-arrays': 'error',
      'no-this-before-super': 'error',
      'no-unassigned-vars': 'error',
      'no-undef': 'error',
      'no-unexpected-multiline': 'error',
      'no-unreachable': 'error',
      'no-unsafe-finally': 'error',
      'no-unsafe-negation': 'error',
      'no-unsafe-optional-chaining': 'error',
      'no-unused-labels': 'error',
      'no-unused-private-class-members': 'error',
      'no-unused-vars': 'error',
      'no-useless-assignment': 'error',
      'no-useless-backreference': 'error',
      'no-useless-catch': 'error',
      'no-useless-escape': 'error',
      'no-with': 'error',
      'preserve-caught-error': 'error',
      'require-yield': 'error',
      'use-isnan': 'error',
      'valid-typeof': 'error',
      'no-array-constructor': 'error',
      'no-unused-expressions': 'error',
      'accessor-pairs': 'error',
      'array-callback-return': 'error',
      'default-case-last': 'error',
      'default-param-last': 'error',
      eqeqeq: 'error',
      'guard-for-in': 'error',
      'no-alert': 'error',
      'no-caller': 'error',
      'no-console': 'error',
      'no-eval': 'error',
      'no-extend-native': 'error',
      'no-extra-bind': 'error',
      'no-implicit-coercion': 'error',
      'no-implied-eval': 'error',
      'no-iterator': 'error',
      'no-labels': 'error',
      'no-label-var': 'error',
      'no-lone-blocks': 'error',
      'no-loop-func': 'error',
      'no-multi-str': 'error',
      'no-new': 'error',
      'no-new-func': 'error',
      'no-new-wrappers': 'error',
      'no-object-constructor': 'error',
      'no-promise-executor-return': 'error',
      'no-proto': 'error',
      'no-return-assign': 'error',
      'no-script-url': 'error',
      'no-self-compare': 'error',
      'no-sequences': 'error',
      'no-shadow': [
        'error',
        {
          hoist: 'all',
        },
      ],
      'no-template-curly-in-string': 'error',
      'no-throw-literal': 'error',
      'no-use-before-define': 'error',
      'prefer-promise-reject-errors': 'error',
      radix: 'error',
      'require-await': 'error',
      'arrow-body-style': 'error',
      'logical-assignment-operators': 'error',
      'no-useless-computed-key': 'error',
      'no-useless-concat': 'error',
      'no-useless-rename': 'error',
      'no-useless-return': 'error',
      'no-var': 'error',
      'object-shorthand': [
        'error',
        'always',
        {
          avoidQuotes: true,
        },
      ],
      'prefer-arrow-callback': 'error',
      'prefer-const': 'error',
      'prefer-object-has-own': 'error',
      'prefer-object-spread': 'error',
      'prefer-regex-literals': 'error',
      'prefer-rest-params': 'error',
      'prefer-spread': 'error',
      'prefer-template': 'error',
      curly: 'error',
      'max-nested-callbacks': [
        'error',
        {
          max: 3,
        },
      ],
      'new-cap': 'error',
      'no-else-return': 'error',
      'no-nested-ternary': 'error',
      'no-unneeded-ternary': 'error',
      'one-var': [
        'error',
        {
          var: 'never',
          let: 'never',
          const: 'never',
        },
      ],
      'unicode-bom': 'error',
      yoda: 'error',
      'jsx-a11y/alt-text': 'error',
      'jsx-a11y/anchor-has-content': 'error',
      'jsx-a11y/anchor-is-valid': 'error',
      'jsx-a11y/aria-activedescendant-has-tabindex': 'error',
      'jsx-a11y/aria-props': 'error',
      'jsx-a11y/aria-proptypes': 'error',
      'jsx-a11y/aria-role': 'error',
      'jsx-a11y/aria-unsupported-elements': 'error',
      'jsx-a11y/autocomplete-valid': 'error',
      'jsx-a11y/click-events-have-key-events': 'error',
      'jsx-a11y/control-has-associated-label': [
        'off',
        {
          ignoreElements: ['audio', 'canvas', 'embed', 'input', 'textarea', 'tr', 'video'],
          ignoreRoles: [
            'grid',
            'listbox',
            'menu',
            'menubar',
            'radiogroup',
            'row',
            'tablist',
            'toolbar',
            'tree',
            'treegrid',
          ],
        },
      ],
      'jsx-a11y/heading-has-content': 'error',
      'jsx-a11y/html-has-lang': 'error',
      'jsx-a11y/iframe-has-title': 'error',
      'jsx-a11y/img-redundant-alt': 'error',
      'jsx-a11y/interactive-supports-focus': [
        'error',
        {
          tabbable: ['button', 'checkbox', 'link', 'searchbox', 'spinbutton', 'switch', 'textbox'],
        },
      ],
      'jsx-a11y/label-has-associated-control': 'error',
      'jsx-a11y/media-has-caption': 'error',
      'jsx-a11y/mouse-events-have-key-events': 'error',
      'jsx-a11y/no-access-key': 'error',
      'jsx-a11y/no-autofocus': 'error',
      'jsx-a11y/no-distracting-elements': 'error',
      'jsx-a11y/no-interactive-element-to-noninteractive-role': [
        'error',
        {
          tr: ['none', 'presentation'],
          canvas: ['img'],
        },
      ],
      'jsx-a11y/no-noninteractive-element-interactions': [
        'error',
        {
          handlers: [
            'onClick',
            'onError',
            'onLoad',
            'onMouseDown',
            'onMouseUp',
            'onKeyPress',
            'onKeyDown',
            'onKeyUp',
          ],
          alert: ['onKeyUp', 'onKeyDown', 'onKeyPress'],
          body: ['onError', 'onLoad'],
          dialog: ['onKeyUp', 'onKeyDown', 'onKeyPress'],
          iframe: ['onError', 'onLoad'],
          img: ['onError', 'onLoad'],
        },
      ],
      'jsx-a11y/no-noninteractive-element-to-interactive-role': [
        'error',
        {
          ul: ['listbox', 'menu', 'menubar', 'radiogroup', 'tablist', 'tree', 'treegrid'],
          ol: ['listbox', 'menu', 'menubar', 'radiogroup', 'tablist', 'tree', 'treegrid'],
          li: ['menuitem', 'menuitemradio', 'menuitemcheckbox', 'option', 'row', 'tab', 'treeitem'],
          table: ['grid'],
          td: ['gridcell'],
          fieldset: ['radiogroup', 'presentation'],
        },
      ],
      'jsx-a11y/no-noninteractive-tabindex': [
        'error',
        {
          tags: [],
          roles: ['tabpanel'],
          allowExpressionValues: true,
        },
      ],
      'jsx-a11y/no-redundant-roles': 'error',
      'jsx-a11y/no-static-element-interactions': [
        'error',
        {
          allowExpressionValues: true,
          handlers: ['onClick', 'onMouseDown', 'onMouseUp', 'onKeyPress', 'onKeyDown', 'onKeyUp'],
        },
      ],
      'jsx-a11y/role-has-required-aria-props': 'error',
      'jsx-a11y/role-supports-aria-props': 'error',
      'jsx-a11y/scope': 'error',
      'jsx-a11y/tabindex-no-positive': 'error',
      'react/rules-of-hooks': 'error',
      'react/static-components': 'error',
      'react/use-memo': 'error',
      'react/preserve-manual-memoization': 'error',
      'react/immutability': 'error',
      'react/globals': 'error',
      'react/refs': 'error',
      'react/set-state-in-effect': 'error',
      'react/error-boundaries': 'error',
      'react/purity': 'error',
      'react/set-state-in-render': 'error',
      'react/unsupported-syntax': 'warn',
      'typescript/ban-ts-comment': 'error',
      'typescript/no-duplicate-enum-values': 'error',
      'typescript/no-empty-object-type': 'error',
      'typescript/no-explicit-any': 'error',
      'typescript/no-extra-non-null-assertion': 'error',
      'typescript/no-misused-new': 'error',
      'typescript/no-namespace': 'error',
      'typescript/no-non-null-asserted-optional-chain': 'error',
      'typescript/no-require-imports': 'error',
      'typescript/no-this-alias': 'error',
      'typescript/no-unnecessary-type-constraint': 'error',
      'typescript/no-unsafe-declaration-merging': 'error',
      'typescript/no-unsafe-function-type': 'error',
      'typescript/no-wrapper-object-types': 'error',
      'typescript/prefer-as-const': 'error',
      'typescript/prefer-namespace-keyword': 'error',
      'typescript/triple-slash-reference': 'error',
      'typescript/consistent-return': 'error',
      'typescript/dot-notation': 'error',
      'vite-plus/prefer-vite-plus-imports': 'error',
    },
    overrides: [
      {
        files: ['**/*.ts', '**/*.tsx', '**/*.mts', '**/*.cts'],
        rules: {
          'constructor-super': 'off',
          'getter-return': 'off',
          'no-class-assign': 'off',
          'no-const-assign': 'off',
          'no-dupe-class-members': 'off',
          'no-dupe-keys': 'off',
          'no-func-assign': 'off',
          'no-import-assign': 'off',
          'no-new-native-nonconstructor': 'off',
          'no-obj-calls': 'off',
          'no-redeclare': 'off',
          'no-setter-return': 'off',
          'no-this-before-super': 'off',
          'no-undef': 'off',
          'no-unreachable': 'off',
          'no-unsafe-negation': 'off',
          'no-with': 'off',
        },
      },
      {
        files: ['**/*.{ts,tsx,mts,cts}'],
        rules: {
          'constructor-super': 'off',
          'getter-return': 'off',
          'no-class-assign': 'off',
          'no-const-assign': 'off',
          'no-dupe-class-members': 'off',
          'no-dupe-keys': 'off',
          'no-func-assign': 'off',
          'no-import-assign': 'off',
          'no-new-native-nonconstructor': 'off',
          'no-obj-calls': 'off',
          'no-redeclare': 'off',
          'no-setter-return': 'off',
          'no-this-before-super': 'off',
          'no-undef': 'off',
          'no-unreachable': 'off',
          'no-unsafe-negation': 'off',
          'no-with': 'off',
          'no-implied-eval': 'off',
          'no-useless-constructor': 'error',
          'no-throw-literal': 'off',
          'prefer-promise-reject-errors': 'off',
          'require-await': 'off',
          'typescript/await-thenable': 'error',
          'typescript/ban-ts-comment': [
            'error',
            {
              minimumDescriptionLength: 10,
            },
          ],
          'typescript/no-array-delete': 'error',
          'typescript/no-base-to-string': 'error',
          'typescript/no-confusing-void-expression': 'error',
          'typescript/no-deprecated': 'error',
          'typescript/no-duplicate-type-constituents': 'error',
          'typescript/no-dynamic-delete': 'error',
          'typescript/no-extraneous-class': 'error',
          'typescript/no-floating-promises': 'error',
          'typescript/no-for-in-array': 'error',
          'typescript/no-implied-eval': 'error',
          'typescript/no-invalid-void-type': 'error',
          'typescript/no-meaningless-void-operator': 'error',
          'typescript/no-misused-promises': 'error',
          'typescript/no-misused-spread': 'error',
          'typescript/no-mixed-enums': 'error',
          'typescript/no-non-null-asserted-nullish-coalescing': 'error',
          'typescript/no-non-null-assertion': 'error',
          'typescript/no-redundant-type-constituents': 'error',
          'typescript/no-unnecessary-boolean-literal-compare': 'error',
          'typescript/no-unnecessary-condition': 'error',
          'typescript/no-unnecessary-template-expression': 'error',
          'typescript/no-unnecessary-type-arguments': 'error',
          'typescript/no-unnecessary-type-assertion': 'error',
          'typescript/no-unnecessary-type-conversion': 'error',
          'typescript/no-unnecessary-type-parameters': 'error',
          'typescript/no-unsafe-argument': 'warn',
          'typescript/no-unsafe-assignment': 'warn',
          'typescript/no-unsafe-call': 'warn',
          'typescript/no-unsafe-enum-comparison': 'error',
          'typescript/no-unsafe-member-access': 'warn',
          'typescript/no-unsafe-return': 'warn',
          'typescript/no-unsafe-unary-minus': 'error',
          'typescript/no-useless-default-assignment': 'error',
          'typescript/only-throw-error': 'error',
          'typescript/prefer-literal-enum-member': 'error',
          'typescript/prefer-promise-reject-errors': 'error',
          'typescript/prefer-reduce-type-parameter': 'error',
          'typescript/prefer-return-this-type': 'error',
          'typescript/related-getter-setter-pairs': 'error',
          'typescript/require-await': 'error',
          'typescript/restrict-plus-operands': [
            'error',
            {
              allowAny: false,
              allowBoolean: false,
              allowNullish: false,
              allowNumberAndString: false,
              allowRegExp: false,
            },
          ],
          'typescript/restrict-template-expressions': [
            'error',
            {
              allowAny: false,
              allowBoolean: false,
              allowNever: false,
              allowNullish: false,
              allowNumber: false,
              allowRegExp: false,
            },
          ],
          'typescript/return-await': ['error', 'error-handling-correctness-only'],
          'typescript/unbound-method': 'error',
          'typescript/unified-signatures': 'error',
          'typescript/use-unknown-in-catch-callback-variable': 'error',
          'no-empty-function': 'error',
          'typescript/adjacent-overload-signatures': 'error',
          'typescript/array-type': 'error',
          'typescript/ban-tslint-comment': 'error',
          'typescript/class-literal-property-style': 'error',
          'typescript/consistent-generic-constructors': 'error',
          'typescript/consistent-indexed-object-style': 'error',
          'typescript/consistent-type-assertions': 'error',
          'typescript/consistent-type-definitions': 'error',
          'typescript/dot-notation': 'off',
          'typescript/no-confusing-non-null-assertion': 'error',
          'typescript/no-inferrable-types': 'error',
          'typescript/non-nullable-type-assertion-style': 'error',
          'typescript/prefer-find': 'error',
          'typescript/prefer-for-of': 'error',
          'typescript/prefer-function-type': 'error',
          'typescript/prefer-includes': 'error',
          'typescript/prefer-nullish-coalescing': 'error',
          'typescript/prefer-optional-chain': 'error',
          'typescript/prefer-regexp-exec': 'error',
          'typescript/prefer-string-starts-ends-with': 'error',
          'no-shadow': [
            'error',
            {
              hoist: 'all',
            },
          ],
          'no-unused-vars': [
            'error',
            {
              args: 'after-used',
              argsIgnorePattern: '^_',
              varsIgnorePattern: '^_',
              caughtErrorsIgnorePattern: '^_',
              destructuredArrayIgnorePattern: '^_',
            },
          ],
          'new-cap': [
            'error',
            {
              capIsNew: false,
            },
          ],
          'typescript/consistent-type-imports': 'error',
          'typescript/consistent-type-exports': 'error',
        },
      },
      {
        files: ['**/*.{ts,tsx}'],
        rules: {
          'typescript/no-useless-empty-export': 'warn',
        },
        jsPlugins: [],
      },
      {
        files: ['src/**/*.{ts,tsx}'],
        rules: {
          'react/only-export-components': 'warn',
        },
        env: {
          es2026: true,
        },
      },
      {
        files: ['**/__tests__/**/*', '**/*test*'],
        rules: {
          'typescript/unbound-method': 'off',
        },
      },
    ],
  },
  plugins: lazyPlugins(() => [react()]),
  test: {
    globals: true,
    environment: 'jsdom',
    setupFiles: ['./src/setupTests.ts'],
  },
});
