services:
  frontend:
    build:
      context: ../frontend
      dockerfile: ../docker/Dockerfile.frontend
    ports:
      - "80:5173"
    volumes:
      - ../frontend:/app
      - /app/node_modules
